# Generated by Django 4.2.1 on 2023-06-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='senderName',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='messages',
            field=models.CharField(max_length=300),
        ),
    ]
