# Generated by Django 4.2.3 on 2023-07-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_product_vendor_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField()),
                ('total', models.IntegerField()),
                ('shiping', models.FloatField()),
                ('quantity', models.PositiveIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('addproducts', models.ManyToManyField(to='inventory.product')),
            ],
        ),
    ]
