# Generated by Django 4.2.3 on 2023-07-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_cart_order_customer_order_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
